name: PR Checks

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]


jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      benchmark_data_tools: ${{ steps.filter.outputs.benchmark_data_tools }}
    steps:
      - name: Checkout velox-testing
        uses: actions/checkout@v4
      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            benchmark_data_tools:
              - "benchmark_data_tools/**"

  test_benchmark_data_tools:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.benchmark_data_tools == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test benchmark_data_tools
        uses: ./.github/actions/test-benchmark-data-tools
