name: Velox Nightly Test (Staging)

on:
  schedule:
    - cron: '0 5 * * *'  # daily at 05:00 UTC
  workflow_dispatch:

jobs:
  nightly-test:
    uses: ./.github/workflows/velox-test.yml
    with:
      repository: ${{ vars.STABLE_VELOX_REPO }}
      velox_commit: ${{ vars.STABLE_VELOX_COMMIT }}
      build_target: 'all'
    secrets: inherit
