name: Velox Nightly Test (Staging)

on:
  schedule:
    - cron: '0 5 * * *'  # daily at 05:00 UTC
  workflow_dispatch:

jobs:
  velox-staging:
    uses: ./.github/workflows/velox-create-staging-if-needed.yml
    with:
      force_push: true
    secrets: inherit

  nightly-test:
    needs:
      - velox-staging
    uses: ./.github/workflows/velox-test.yml
    if: ${{ needs.velox-staging.result == 'success' && needs.velox-staging.outputs.has_staging_branch == 'true' }}
    with:
      repository: ${{ needs.velox-staging.outputs.staging_repository }}
      velox_commit: ${{ needs.velox-staging.outputs.staging_branch }}
      build_target: 'all'
      use_upstream_deps_image: ${{ vars.STABLE_VELOX_USE_UPSTREAM_DEPS_IMAGE == 'true' }}
    secrets: inherit
